use serde::{Deserialize, Serialize};

use crate::{Digest, EmberResult};

#[derive(Copy, Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct ControlTemplate {
    pub id: &'static str,
    pub family: &'static str,
    pub phase: &'static str,
    pub subject: &'static str,
    pub weight_bps: u16,
    pub enabled: bool,
}

pub const CONTROL_MATRIX: &[ControlTemplate] = &[
    ControlTemplate {
        id: "EBR-ADMI-0001",
        family: "admission",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 62,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0002",
        family: "costing",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 99,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0003",
        family: "rebate",
        phase: "execute",
        subject: "time band",
        weight_bps: 136,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0004",
        family: "pool",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 173,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0005",
        family: "settlement",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 210,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0006",
        family: "operator",
        phase: "report",
        subject: "journal trace",
        weight_bps: 247,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0007",
        family: "journal",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 284,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0008",
        family: "latency",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 321,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0009",
        family: "liquidity",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 358,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0010",
        family: "governance",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 395,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0011",
        family: "admission",
        phase: "reconcile",
        subject: "capacity view",
        weight_bps: 432,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0012",
        family: "costing",
        phase: "report",
        subject: "latency lane",
        weight_bps: 469,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0013",
        family: "rebate",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 506,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0014",
        family: "pool",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 543,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0015",
        family: "settlement",
        phase: "execute",
        subject: "time band",
        weight_bps: 580,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0016",
        family: "operator",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 617,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0017",
        family: "journal",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 654,
        enabled: false,
    },
    ControlTemplate {
        id: "EBR-LATE-0018",
        family: "latency",
        phase: "report",
        subject: "journal trace",
        weight_bps: 691,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0019",
        family: "liquidity",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 728,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0020",
        family: "governance",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 765,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0021",
        family: "admission",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 802,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0022",
        family: "costing",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 839,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0023",
        family: "rebate",
        phase: "reconcile",
        subject: "capacity view",
        weight_bps: 876,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0024",
        family: "pool",
        phase: "report",
        subject: "latency lane",
        weight_bps: 913,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0025",
        family: "settlement",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 50,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0026",
        family: "operator",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 87,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0027",
        family: "journal",
        phase: "execute",
        subject: "time band",
        weight_bps: 124,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0028",
        family: "latency",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 161,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0029",
        family: "liquidity",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 198,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0030",
        family: "governance",
        phase: "report",
        subject: "journal trace",
        weight_bps: 235,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0031",
        family: "admission",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 272,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0032",
        family: "costing",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 309,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0033",
        family: "rebate",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 346,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0034",
        family: "pool",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 383,
        enabled: false,
    },
    ControlTemplate {
        id: "EBR-SETT-0035",
        family: "settlement",
        phase: "reconcile",
        subject: "capacity view",
        weight_bps: 420,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0036",
        family: "operator",
        phase: "report",
        subject: "latency lane",
        weight_bps: 457,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0037",
        family: "journal",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 494,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0038",
        family: "latency",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 531,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0039",
        family: "liquidity",
        phase: "execute",
        subject: "time band",
        weight_bps: 568,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0040",
        family: "governance",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 605,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0041",
        family: "admission",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 642,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0042",
        family: "costing",
        phase: "report",
        subject: "journal trace",
        weight_bps: 679,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0043",
        family: "rebate",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 716,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0044",
        family: "pool",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 753,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0045",
        family: "settlement",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 790,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0046",
        family: "operator",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 827,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0047",
        family: "journal",
        phase: "reconcile",
        subject: "capacity view",
        weight_bps: 864,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0048",
        family: "latency",
        phase: "report",
        subject: "latency lane",
        weight_bps: 901,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0049",
        family: "liquidity",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 38,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0050",
        family: "governance",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 75,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0051",
        family: "admission",
        phase: "execute",
        subject: "time band",
        weight_bps: 112,
        enabled: false,
    },
    ControlTemplate {
        id: "EBR-COST-0052",
        family: "costing",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 149,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0053",
        family: "rebate",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 186,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0054",
        family: "pool",
        phase: "report",
        subject: "journal trace",
        weight_bps: 223,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0055",
        family: "settlement",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 260,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0056",
        family: "operator",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 297,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0057",
        family: "journal",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 334,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0058",
        family: "latency",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 371,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0059",
        family: "liquidity",
        phase: "reconcile",
        subject: "capacity view",
        weight_bps: 408,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0060",
        family: "governance",
        phase: "report",
        subject: "latency lane",
        weight_bps: 445,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0061",
        family: "admission",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 482,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0062",
        family: "costing",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 519,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0063",
        family: "rebate",
        phase: "execute",
        subject: "time band",
        weight_bps: 556,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0064",
        family: "pool",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 593,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0065",
        family: "settlement",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 630,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0066",
        family: "operator",
        phase: "report",
        subject: "journal trace",
        weight_bps: 667,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0067",
        family: "journal",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 704,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0068",
        family: "latency",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 741,
        enabled: false,
    },
    ControlTemplate {
        id: "EBR-LIQU-0069",
        family: "liquidity",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 778,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0070",
        family: "governance",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 815,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0071",
        family: "admission",
        phase: "reconcile",
        subject: "capacity view",
        weight_bps: 852,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0072",
        family: "costing",
        phase: "report",
        subject: "latency lane",
        weight_bps: 889,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0073",
        family: "rebate",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 26,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0074",
        family: "pool",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 63,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0075",
        family: "settlement",
        phase: "execute",
        subject: "time band",
        weight_bps: 100,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0076",
        family: "operator",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 137,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0077",
        family: "journal",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 174,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0078",
        family: "latency",
        phase: "report",
        subject: "journal trace",
        weight_bps: 211,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0079",
        family: "liquidity",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 248,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0080",
        family: "governance",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 285,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0081",
        family: "admission",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 322,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0082",
        family: "costing",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 359,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0083",
        family: "rebate",
        phase: "reconcile",
        subject: "capacity view",
        weight_bps: 396,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0084",
        family: "pool",
        phase: "report",
        subject: "latency lane",
        weight_bps: 433,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0085",
        family: "settlement",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 470,
        enabled: false,
    },
    ControlTemplate {
        id: "EBR-OPER-0086",
        family: "operator",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 507,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0087",
        family: "journal",
        phase: "execute",
        subject: "time band",
        weight_bps: 544,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0088",
        family: "latency",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 581,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0089",
        family: "liquidity",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 618,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0090",
        family: "governance",
        phase: "report",
        subject: "journal trace",
        weight_bps: 655,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0091",
        family: "admission",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 692,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0092",
        family: "costing",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 729,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0093",
        family: "rebate",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 766,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0094",
        family: "pool",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 803,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0095",
        family: "settlement",
        phase: "reconcile",
        subject: "capacity view",
        weight_bps: 840,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0096",
        family: "operator",
        phase: "report",
        subject: "latency lane",
        weight_bps: 877,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0097",
        family: "journal",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 914,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0098",
        family: "latency",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 51,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0099",
        family: "liquidity",
        phase: "execute",
        subject: "time band",
        weight_bps: 88,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0100",
        family: "governance",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 125,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0101",
        family: "admission",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 162,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0102",
        family: "costing",
        phase: "report",
        subject: "journal trace",
        weight_bps: 199,
        enabled: false,
    },
    ControlTemplate {
        id: "EBR-REBA-0103",
        family: "rebate",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 236,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0104",
        family: "pool",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 273,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0105",
        family: "settlement",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 310,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0106",
        family: "operator",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 347,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0107",
        family: "journal",
        phase: "reconcile",
        subject: "capacity view",
        weight_bps: 384,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0108",
        family: "latency",
        phase: "report",
        subject: "latency lane",
        weight_bps: 421,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0109",
        family: "liquidity",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 458,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0110",
        family: "governance",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 495,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0111",
        family: "admission",
        phase: "execute",
        subject: "time band",
        weight_bps: 532,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0112",
        family: "costing",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 569,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0113",
        family: "rebate",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 606,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0114",
        family: "pool",
        phase: "report",
        subject: "journal trace",
        weight_bps: 643,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0115",
        family: "settlement",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 680,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0116",
        family: "operator",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 717,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0117",
        family: "journal",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 754,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0118",
        family: "latency",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 791,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0119",
        family: "liquidity",
        phase: "reconcile",
        subject: "capacity view",
        weight_bps: 828,
        enabled: false,
    },
    ControlTemplate {
        id: "EBR-GOVE-0120",
        family: "governance",
        phase: "report",
        subject: "latency lane",
        weight_bps: 865,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0121",
        family: "admission",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 902,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0122",
        family: "costing",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 39,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0123",
        family: "rebate",
        phase: "execute",
        subject: "time band",
        weight_bps: 76,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0124",
        family: "pool",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 113,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0125",
        family: "settlement",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 150,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0126",
        family: "operator",
        phase: "report",
        subject: "journal trace",
        weight_bps: 187,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0127",
        family: "journal",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 224,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0128",
        family: "latency",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 261,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0129",
        family: "liquidity",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 298,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0130",
        family: "governance",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 335,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0131",
        family: "admission",
        phase: "reconcile",
        subject: "capacity view",
        weight_bps: 372,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0132",
        family: "costing",
        phase: "report",
        subject: "latency lane",
        weight_bps: 409,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0133",
        family: "rebate",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 446,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0134",
        family: "pool",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 483,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0135",
        family: "settlement",
        phase: "execute",
        subject: "time band",
        weight_bps: 520,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0136",
        family: "operator",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 557,
        enabled: false,
    },
    ControlTemplate {
        id: "EBR-JOUR-0137",
        family: "journal",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 594,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0138",
        family: "latency",
        phase: "report",
        subject: "journal trace",
        weight_bps: 631,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0139",
        family: "liquidity",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 668,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0140",
        family: "governance",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 705,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0141",
        family: "admission",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 742,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0142",
        family: "costing",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 779,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0143",
        family: "rebate",
        phase: "reconcile",
        subject: "capacity view",
        weight_bps: 816,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0144",
        family: "pool",
        phase: "report",
        subject: "latency lane",
        weight_bps: 853,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0145",
        family: "settlement",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 890,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0146",
        family: "operator",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 27,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0147",
        family: "journal",
        phase: "execute",
        subject: "time band",
        weight_bps: 64,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0148",
        family: "latency",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 101,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0149",
        family: "liquidity",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 138,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0150",
        family: "governance",
        phase: "report",
        subject: "journal trace",
        weight_bps: 175,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0151",
        family: "admission",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 212,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0152",
        family: "costing",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 249,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0153",
        family: "rebate",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 286,
        enabled: false,
    },
    ControlTemplate {
        id: "EBR-POOL-0154",
        family: "pool",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 323,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0155",
        family: "settlement",
        phase: "reconcile",
        subject: "capacity view",
        weight_bps: 360,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0156",
        family: "operator",
        phase: "report",
        subject: "latency lane",
        weight_bps: 397,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0157",
        family: "journal",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 434,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0158",
        family: "latency",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 471,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0159",
        family: "liquidity",
        phase: "execute",
        subject: "time band",
        weight_bps: 508,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0160",
        family: "governance",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 545,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0161",
        family: "admission",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 582,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0162",
        family: "costing",
        phase: "report",
        subject: "journal trace",
        weight_bps: 619,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0163",
        family: "rebate",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 656,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0164",
        family: "pool",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 693,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0165",
        family: "settlement",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 730,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0166",
        family: "operator",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 767,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0167",
        family: "journal",
        phase: "reconcile",
        subject: "capacity view",
        weight_bps: 804,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0168",
        family: "latency",
        phase: "report",
        subject: "latency lane",
        weight_bps: 841,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0169",
        family: "liquidity",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 878,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0170",
        family: "governance",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 915,
        enabled: false,
    },
    ControlTemplate {
        id: "EBR-ADMI-0171",
        family: "admission",
        phase: "execute",
        subject: "time band",
        weight_bps: 52,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0172",
        family: "costing",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 89,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0173",
        family: "rebate",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 126,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0174",
        family: "pool",
        phase: "report",
        subject: "journal trace",
        weight_bps: 163,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0175",
        family: "settlement",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 200,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0176",
        family: "operator",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 237,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0177",
        family: "journal",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 274,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0178",
        family: "latency",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 311,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0179",
        family: "liquidity",
        phase: "reconcile",
        subject: "capacity view",
        weight_bps: 348,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0180",
        family: "governance",
        phase: "report",
        subject: "latency lane",
        weight_bps: 385,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0181",
        family: "admission",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 422,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0182",
        family: "costing",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 459,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0183",
        family: "rebate",
        phase: "execute",
        subject: "time band",
        weight_bps: 496,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0184",
        family: "pool",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 533,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0185",
        family: "settlement",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 570,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0186",
        family: "operator",
        phase: "report",
        subject: "journal trace",
        weight_bps: 607,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0187",
        family: "journal",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 644,
        enabled: false,
    },
    ControlTemplate {
        id: "EBR-LATE-0188",
        family: "latency",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 681,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0189",
        family: "liquidity",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 718,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0190",
        family: "governance",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 755,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0191",
        family: "admission",
        phase: "reconcile",
        subject: "capacity view",
        weight_bps: 792,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0192",
        family: "costing",
        phase: "report",
        subject: "latency lane",
        weight_bps: 829,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0193",
        family: "rebate",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 866,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0194",
        family: "pool",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 903,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0195",
        family: "settlement",
        phase: "execute",
        subject: "time band",
        weight_bps: 40,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0196",
        family: "operator",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 77,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0197",
        family: "journal",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 114,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0198",
        family: "latency",
        phase: "report",
        subject: "journal trace",
        weight_bps: 151,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0199",
        family: "liquidity",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 188,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0200",
        family: "governance",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 225,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0201",
        family: "admission",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 262,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0202",
        family: "costing",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 299,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0203",
        family: "rebate",
        phase: "reconcile",
        subject: "capacity view",
        weight_bps: 336,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0204",
        family: "pool",
        phase: "report",
        subject: "latency lane",
        weight_bps: 373,
        enabled: false,
    },
    ControlTemplate {
        id: "EBR-SETT-0205",
        family: "settlement",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 410,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0206",
        family: "operator",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 447,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0207",
        family: "journal",
        phase: "execute",
        subject: "time band",
        weight_bps: 484,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0208",
        family: "latency",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 521,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0209",
        family: "liquidity",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 558,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0210",
        family: "governance",
        phase: "report",
        subject: "journal trace",
        weight_bps: 595,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0211",
        family: "admission",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 632,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0212",
        family: "costing",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 669,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0213",
        family: "rebate",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 706,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0214",
        family: "pool",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 743,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0215",
        family: "settlement",
        phase: "reconcile",
        subject: "capacity view",
        weight_bps: 780,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0216",
        family: "operator",
        phase: "report",
        subject: "latency lane",
        weight_bps: 817,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0217",
        family: "journal",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 854,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0218",
        family: "latency",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 891,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0219",
        family: "liquidity",
        phase: "execute",
        subject: "time band",
        weight_bps: 28,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0220",
        family: "governance",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 65,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0221",
        family: "admission",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 102,
        enabled: false,
    },
    ControlTemplate {
        id: "EBR-COST-0222",
        family: "costing",
        phase: "report",
        subject: "journal trace",
        weight_bps: 139,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0223",
        family: "rebate",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 176,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0224",
        family: "pool",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 213,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0225",
        family: "settlement",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 250,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0226",
        family: "operator",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 287,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0227",
        family: "journal",
        phase: "reconcile",
        subject: "capacity view",
        weight_bps: 324,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0228",
        family: "latency",
        phase: "report",
        subject: "latency lane",
        weight_bps: 361,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0229",
        family: "liquidity",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 398,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0230",
        family: "governance",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 435,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0231",
        family: "admission",
        phase: "execute",
        subject: "time band",
        weight_bps: 472,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0232",
        family: "costing",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 509,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0233",
        family: "rebate",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 546,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0234",
        family: "pool",
        phase: "report",
        subject: "journal trace",
        weight_bps: 583,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0235",
        family: "settlement",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 620,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0236",
        family: "operator",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 657,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0237",
        family: "journal",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 694,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0238",
        family: "latency",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 731,
        enabled: false,
    },
    ControlTemplate {
        id: "EBR-LIQU-0239",
        family: "liquidity",
        phase: "reconcile",
        subject: "capacity view",
        weight_bps: 768,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0240",
        family: "governance",
        phase: "report",
        subject: "latency lane",
        weight_bps: 805,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0241",
        family: "admission",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 842,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0242",
        family: "costing",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 879,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0243",
        family: "rebate",
        phase: "execute",
        subject: "time band",
        weight_bps: 916,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0244",
        family: "pool",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 53,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0245",
        family: "settlement",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 90,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0246",
        family: "operator",
        phase: "report",
        subject: "journal trace",
        weight_bps: 127,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0247",
        family: "journal",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 164,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0248",
        family: "latency",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 201,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0249",
        family: "liquidity",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 238,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0250",
        family: "governance",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 275,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0251",
        family: "admission",
        phase: "reconcile",
        subject: "capacity view",
        weight_bps: 312,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0252",
        family: "costing",
        phase: "report",
        subject: "latency lane",
        weight_bps: 349,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0253",
        family: "rebate",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 386,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0254",
        family: "pool",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 423,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0255",
        family: "settlement",
        phase: "execute",
        subject: "time band",
        weight_bps: 460,
        enabled: false,
    },
    ControlTemplate {
        id: "EBR-OPER-0256",
        family: "operator",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 497,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0257",
        family: "journal",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 534,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0258",
        family: "latency",
        phase: "report",
        subject: "journal trace",
        weight_bps: 571,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0259",
        family: "liquidity",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 608,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0260",
        family: "governance",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 645,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0261",
        family: "admission",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 682,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0262",
        family: "costing",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 719,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0263",
        family: "rebate",
        phase: "reconcile",
        subject: "capacity view",
        weight_bps: 756,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0264",
        family: "pool",
        phase: "report",
        subject: "latency lane",
        weight_bps: 793,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0265",
        family: "settlement",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 830,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0266",
        family: "operator",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 867,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0267",
        family: "journal",
        phase: "execute",
        subject: "time band",
        weight_bps: 904,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0268",
        family: "latency",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 41,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0269",
        family: "liquidity",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 78,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0270",
        family: "governance",
        phase: "report",
        subject: "journal trace",
        weight_bps: 115,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0271",
        family: "admission",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 152,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0272",
        family: "costing",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 189,
        enabled: false,
    },
    ControlTemplate {
        id: "EBR-REBA-0273",
        family: "rebate",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 226,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0274",
        family: "pool",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 263,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0275",
        family: "settlement",
        phase: "reconcile",
        subject: "capacity view",
        weight_bps: 300,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0276",
        family: "operator",
        phase: "report",
        subject: "latency lane",
        weight_bps: 337,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0277",
        family: "journal",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 374,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0278",
        family: "latency",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 411,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0279",
        family: "liquidity",
        phase: "execute",
        subject: "time band",
        weight_bps: 448,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0280",
        family: "governance",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 485,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0281",
        family: "admission",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 522,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0282",
        family: "costing",
        phase: "report",
        subject: "journal trace",
        weight_bps: 559,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0283",
        family: "rebate",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 596,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0284",
        family: "pool",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 633,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0285",
        family: "settlement",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 670,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0286",
        family: "operator",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 707,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0287",
        family: "journal",
        phase: "reconcile",
        subject: "capacity view",
        weight_bps: 744,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0288",
        family: "latency",
        phase: "report",
        subject: "latency lane",
        weight_bps: 781,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0289",
        family: "liquidity",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 818,
        enabled: false,
    },
    ControlTemplate {
        id: "EBR-GOVE-0290",
        family: "governance",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 855,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0291",
        family: "admission",
        phase: "execute",
        subject: "time band",
        weight_bps: 892,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0292",
        family: "costing",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 29,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0293",
        family: "rebate",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 66,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0294",
        family: "pool",
        phase: "report",
        subject: "journal trace",
        weight_bps: 103,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0295",
        family: "settlement",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 140,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0296",
        family: "operator",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 177,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0297",
        family: "journal",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 214,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0298",
        family: "latency",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 251,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0299",
        family: "liquidity",
        phase: "reconcile",
        subject: "capacity view",
        weight_bps: 288,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0300",
        family: "governance",
        phase: "report",
        subject: "latency lane",
        weight_bps: 325,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0301",
        family: "admission",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 362,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0302",
        family: "costing",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 399,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0303",
        family: "rebate",
        phase: "execute",
        subject: "time band",
        weight_bps: 436,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0304",
        family: "pool",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 473,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0305",
        family: "settlement",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 510,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0306",
        family: "operator",
        phase: "report",
        subject: "journal trace",
        weight_bps: 547,
        enabled: false,
    },
    ControlTemplate {
        id: "EBR-JOUR-0307",
        family: "journal",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 584,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0308",
        family: "latency",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 621,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0309",
        family: "liquidity",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 658,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0310",
        family: "governance",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 695,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0311",
        family: "admission",
        phase: "reconcile",
        subject: "capacity view",
        weight_bps: 732,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0312",
        family: "costing",
        phase: "report",
        subject: "latency lane",
        weight_bps: 769,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0313",
        family: "rebate",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 806,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0314",
        family: "pool",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 843,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0315",
        family: "settlement",
        phase: "execute",
        subject: "time band",
        weight_bps: 880,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0316",
        family: "operator",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 917,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0317",
        family: "journal",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 54,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0318",
        family: "latency",
        phase: "report",
        subject: "journal trace",
        weight_bps: 91,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0319",
        family: "liquidity",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 128,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0320",
        family: "governance",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 165,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0321",
        family: "admission",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 202,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0322",
        family: "costing",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 239,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0323",
        family: "rebate",
        phase: "reconcile",
        subject: "capacity view",
        weight_bps: 276,
        enabled: false,
    },
    ControlTemplate {
        id: "EBR-POOL-0324",
        family: "pool",
        phase: "report",
        subject: "latency lane",
        weight_bps: 313,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0325",
        family: "settlement",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 350,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0326",
        family: "operator",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 387,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0327",
        family: "journal",
        phase: "execute",
        subject: "time band",
        weight_bps: 424,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0328",
        family: "latency",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 461,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0329",
        family: "liquidity",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 498,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0330",
        family: "governance",
        phase: "report",
        subject: "journal trace",
        weight_bps: 535,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0331",
        family: "admission",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 572,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0332",
        family: "costing",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 609,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0333",
        family: "rebate",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 646,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0334",
        family: "pool",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 683,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0335",
        family: "settlement",
        phase: "reconcile",
        subject: "capacity view",
        weight_bps: 720,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0336",
        family: "operator",
        phase: "report",
        subject: "latency lane",
        weight_bps: 757,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0337",
        family: "journal",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 794,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0338",
        family: "latency",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 831,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0339",
        family: "liquidity",
        phase: "execute",
        subject: "time band",
        weight_bps: 868,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0340",
        family: "governance",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 905,
        enabled: false,
    },
    ControlTemplate {
        id: "EBR-ADMI-0341",
        family: "admission",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 42,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0342",
        family: "costing",
        phase: "report",
        subject: "journal trace",
        weight_bps: 79,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0343",
        family: "rebate",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 116,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0344",
        family: "pool",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 153,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0345",
        family: "settlement",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 190,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0346",
        family: "operator",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 227,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0347",
        family: "journal",
        phase: "reconcile",
        subject: "capacity view",
        weight_bps: 264,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0348",
        family: "latency",
        phase: "report",
        subject: "latency lane",
        weight_bps: 301,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0349",
        family: "liquidity",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 338,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0350",
        family: "governance",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 375,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0351",
        family: "admission",
        phase: "execute",
        subject: "time band",
        weight_bps: 412,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0352",
        family: "costing",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 449,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0353",
        family: "rebate",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 486,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0354",
        family: "pool",
        phase: "report",
        subject: "journal trace",
        weight_bps: 523,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0355",
        family: "settlement",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 560,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0356",
        family: "operator",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 597,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0357",
        family: "journal",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 634,
        enabled: false,
    },
    ControlTemplate {
        id: "EBR-LATE-0358",
        family: "latency",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 671,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0359",
        family: "liquidity",
        phase: "reconcile",
        subject: "capacity view",
        weight_bps: 708,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0360",
        family: "governance",
        phase: "report",
        subject: "latency lane",
        weight_bps: 745,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0361",
        family: "admission",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 782,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0362",
        family: "costing",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 819,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0363",
        family: "rebate",
        phase: "execute",
        subject: "time band",
        weight_bps: 856,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0364",
        family: "pool",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 893,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0365",
        family: "settlement",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 30,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0366",
        family: "operator",
        phase: "report",
        subject: "journal trace",
        weight_bps: 67,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0367",
        family: "journal",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 104,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0368",
        family: "latency",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 141,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0369",
        family: "liquidity",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 178,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0370",
        family: "governance",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 215,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0371",
        family: "admission",
        phase: "reconcile",
        subject: "capacity view",
        weight_bps: 252,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0372",
        family: "costing",
        phase: "report",
        subject: "latency lane",
        weight_bps: 289,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0373",
        family: "rebate",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 326,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0374",
        family: "pool",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 363,
        enabled: false,
    },
    ControlTemplate {
        id: "EBR-SETT-0375",
        family: "settlement",
        phase: "execute",
        subject: "time band",
        weight_bps: 400,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0376",
        family: "operator",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 437,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0377",
        family: "journal",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 474,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0378",
        family: "latency",
        phase: "report",
        subject: "journal trace",
        weight_bps: 511,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0379",
        family: "liquidity",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 548,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0380",
        family: "governance",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 585,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0381",
        family: "admission",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 622,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0382",
        family: "costing",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 659,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0383",
        family: "rebate",
        phase: "reconcile",
        subject: "capacity view",
        weight_bps: 696,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0384",
        family: "pool",
        phase: "report",
        subject: "latency lane",
        weight_bps: 733,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0385",
        family: "settlement",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 770,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0386",
        family: "operator",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 807,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0387",
        family: "journal",
        phase: "execute",
        subject: "time band",
        weight_bps: 844,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0388",
        family: "latency",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 881,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0389",
        family: "liquidity",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 918,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0390",
        family: "governance",
        phase: "report",
        subject: "journal trace",
        weight_bps: 55,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0391",
        family: "admission",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 92,
        enabled: false,
    },
    ControlTemplate {
        id: "EBR-COST-0392",
        family: "costing",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 129,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0393",
        family: "rebate",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 166,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0394",
        family: "pool",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 203,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0395",
        family: "settlement",
        phase: "reconcile",
        subject: "capacity view",
        weight_bps: 240,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0396",
        family: "operator",
        phase: "report",
        subject: "latency lane",
        weight_bps: 277,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0397",
        family: "journal",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 314,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0398",
        family: "latency",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 351,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0399",
        family: "liquidity",
        phase: "execute",
        subject: "time band",
        weight_bps: 388,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0400",
        family: "governance",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 425,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0401",
        family: "admission",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 462,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0402",
        family: "costing",
        phase: "report",
        subject: "journal trace",
        weight_bps: 499,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0403",
        family: "rebate",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 536,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0404",
        family: "pool",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 573,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0405",
        family: "settlement",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 610,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0406",
        family: "operator",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 647,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0407",
        family: "journal",
        phase: "reconcile",
        subject: "capacity view",
        weight_bps: 684,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0408",
        family: "latency",
        phase: "report",
        subject: "latency lane",
        weight_bps: 721,
        enabled: false,
    },
    ControlTemplate {
        id: "EBR-LIQU-0409",
        family: "liquidity",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 758,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0410",
        family: "governance",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 795,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0411",
        family: "admission",
        phase: "execute",
        subject: "time band",
        weight_bps: 832,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0412",
        family: "costing",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 869,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0413",
        family: "rebate",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 906,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0414",
        family: "pool",
        phase: "report",
        subject: "journal trace",
        weight_bps: 43,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0415",
        family: "settlement",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 80,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-OPER-0416",
        family: "operator",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 117,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0417",
        family: "journal",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 154,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0418",
        family: "latency",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 191,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0419",
        family: "liquidity",
        phase: "reconcile",
        subject: "capacity view",
        weight_bps: 228,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0420",
        family: "governance",
        phase: "report",
        subject: "latency lane",
        weight_bps: 265,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-ADMI-0421",
        family: "admission",
        phase: "quote",
        subject: "route envelope",
        weight_bps: 302,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-COST-0422",
        family: "costing",
        phase: "reserve",
        subject: "cost band",
        weight_bps: 339,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-REBA-0423",
        family: "rebate",
        phase: "execute",
        subject: "time band",
        weight_bps: 376,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-POOL-0424",
        family: "pool",
        phase: "finalize",
        subject: "pool budget",
        weight_bps: 413,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-SETT-0425",
        family: "settlement",
        phase: "reconcile",
        subject: "operator score",
        weight_bps: 450,
        enabled: false,
    },
    ControlTemplate {
        id: "EBR-OPER-0426",
        family: "operator",
        phase: "report",
        subject: "journal trace",
        weight_bps: 487,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-JOUR-0427",
        family: "journal",
        phase: "quote",
        subject: "asset binding",
        weight_bps: 524,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LATE-0428",
        family: "latency",
        phase: "reserve",
        subject: "reserve release",
        weight_bps: 561,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-LIQU-0429",
        family: "liquidity",
        phase: "execute",
        subject: "rebate tier",
        weight_bps: 598,
        enabled: true,
    },
    ControlTemplate {
        id: "EBR-GOVE-0430",
        family: "governance",
        phase: "finalize",
        subject: "settlement receipt",
        weight_bps: 635,
        enabled: true,
    },
];

pub fn reference_digest() -> EmberResult<Digest> {
    Digest::from_serializable("emberline-control-matrix", &CONTROL_MATRIX)
}
